### PR TITLE
Fix escaping

### LINKED ISSUE #13: Unescaped version still escape arguments
I've used pino logger and found that interpolated messages get escaped. So, it happens here.
```js
const util = require('util');
const format = require('quick-format-unescaped');

console.log(util.format('test: %s', 'with \"qoutes\"')); // -> test: with "qoutes"
console.log(format(['test: %s', 'with \"qoutes\"'])); // -> test: with \"qoutes\"
```

### PR DESCRIPTION
**Pull request by yaroslav-korotaev**
Resolves #13

### CODE REVIEW

**Comment by mcollina** [comment]
Can you add a unit test?

**Comment by davidmarkclements** [comment]
thanks for this!

would you mind adding before/after benchmark output?

**Comment by yaroslav-korotaev** [comment]
+-20ms
```
before:
util*100000: 318.775ms
quickLowres*100000: 372.406ms
quick*100000: 424.844ms
utilWithTailObj*100000: 619.407ms
quickWithTailObjLowres*100000: 409.077ms
quickWithTailObj*100000: 461.625ms
util*100000: 310.034ms
quickLowres*100000: 365.254ms
quick*100000: 410.380ms
utilWithTailObj*100000: 511.166ms
quickWithTailObjLowres*100000: 382.802ms
quickWithTailObj*100000: 440.928ms

after:
util*100000: 303.136ms
quickLowres*100000: 307.512ms
quick*100000: 355.228ms
utilWithTailObj*100000: 599.588ms
quickWithTailObjLowres*100000: 350.440ms
quickWithTailObj*100000: 404.619ms
util*100000: 297.329ms
quickLowres*100000: 297.532ms
quick*100000: 345.720ms
utilWithTailObj*100000: 489.627ms
quickWithTailObjLowres*100000: 324.175ms
quickWithTailObj*100000: 390.236ms
```

**Comment by davidmarkclements** [comment]
thank you @yaroslav-korotaev

**Pull request merged**
